# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ngGen1GUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(498, 276)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setAutoFillBackground(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cTempLabel = QtWidgets.QLabel(self.centralwidget)
        self.cTempLabel.setGeometry(QtCore.QRect(280, 9, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.cTempLabel.setFont(font)
        self.cTempLabel.setObjectName("cTempLabel")
        self.currentTemp = QtWidgets.QLCDNumber(self.centralwidget)
        self.currentTemp.setGeometry(QtCore.QRect(280, 30, 181, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.currentTemp.setFont(font)
        self.currentTemp.setAutoFillBackground(True)
        self.currentTemp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.currentTemp.setLineWidth(3)
        self.currentTemp.setObjectName("currentTemp")
        self.btEmStop = QtWidgets.QPushButton(self.centralwidget)
        self.btEmStop.setGeometry(QtCore.QRect(50, 210, 191, 31))
        self.btEmStop.setObjectName("btEmStop")
        self.tbDataButton = QtWidgets.QToolButton(self.centralwidget)
        self.tbDataButton.setGeometry(QtCore.QRect(90, 10, 61, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tbDataButton.setFont(font)
        self.tbDataButton.setObjectName("tbDataButton")
        self.tbSetButton = QtWidgets.QToolButton(self.centralwidget)
        self.tbSetButton.setGeometry(QtCore.QRect(10, 10, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.tbSetButton.setFont(font)
        self.tbSetButton.setObjectName("tbSetButton")
        self.dtempLabel = QtWidgets.QLabel(self.centralwidget)
        self.dtempLabel.setGeometry(QtCore.QRect(280, 149, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setUnderline(False)
        font.setWeight(75)
        self.dtempLabel.setFont(font)
        self.dtempLabel.setObjectName("dtempLabel")
        self.desiredTemp = QtWidgets.QLCDNumber(self.centralwidget)
        self.desiredTemp.setGeometry(QtCore.QRect(280, 170, 181, 81))
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.desiredTemp.setFont(font)
        self.desiredTemp.setAutoFillBackground(True)
        self.desiredTemp.setFrameShadow(QtWidgets.QFrame.Plain)
        self.desiredTemp.setLineWidth(3)
        self.desiredTemp.setObjectName("desiredTemp")
        self.tempSet = QtWidgets.QDoubleSpinBox(self.centralwidget)
        self.tempSet.setGeometry(QtCore.QRect(90, 70, 91, 31))
        self.tempSet.setMinimum(4.0)
        self.tempSet.setMaximum(300.0)
        self.tempSet.setObjectName("tempSet")
        self.btConfirm = QtWidgets.QPushButton(self.centralwidget)
        self.btConfirm.setGeometry(QtCore.QRect(50, 120, 71, 41))
        self.btConfirm.setObjectName("btConfirm")
        self.btStop = QtWidgets.QPushButton(self.centralwidget)
        self.btStop.setGeometry(QtCore.QRect(140, 120, 81, 41))
        self.btStop.setObjectName("btStop")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cTempLabel.setText(_translate("MainWindow", "Current Temp(K)"))
        self.btEmStop.setText(_translate("MainWindow", "Emergency STOP"))
        self.tbDataButton.setText(_translate("MainWindow", "Data"))
        self.tbSetButton.setText(_translate("MainWindow", "Settings"))
        self.dtempLabel.setText(_translate("MainWindow", "Desired Temp(K)"))
        self.btConfirm.setText(_translate("MainWindow", "Apply"))
        self.btStop.setText(_translate("MainWindow", "Cancel"))

